name: AI Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - dev
    types: [opened, reopened, synchronize]

jobs:
  code-review:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'review_requested') }}
    runs-on: ubuntu-latest
    steps:
      - name: ChatGPT
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: gpt-3.5-turbo
          PROMPT: |
            You are a software developer responsible for conducting code reviews in the Engineering department of a technology/software company.
            After reviewing a code submission, generate a comprehensive report summarizing the findings. 
            Include information such as identified issues, recommendations for improvement, areas of strength, and overall code quality assessment. 
            The report should be well-structured, easy to understand, in korean, and provide actionable feedback to the developer.

          top_p: 0.4
          temperature: 0.2
          max_tokens: 4000
          INCLUDE_PATTERNS: '*.js,*.ts,*.jsx,*.tsx'
