name: Run CI

on:
  pull_request:
    branches:
      - dev
      - release

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Request changes on PR, when tests fail
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'REQUEST_CHANGES',
              body: '모든 테스트를 통과하지 못했습니다.'
            })

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Environment variables
        run: |
          touch ./.env.production
          
          echo "${{ secrets.PRODUCTION_ENV }}" > ./.env.production
        shell: bash

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Request changes on PR, when build fails
        if: ${{ failure() }}
        uses: actions/github-script@v6
        env: {}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ref = "${{ github.ref }}"
            const pull_number = Number(ref.split('/')[2])
            
            await github.pulls.createReview({
              ...context.repo,
              pull_number: context.issue.number,
              body: '빌드에 실패했습니다. 코드 / 환경변수 등을 확인해주세요.',
            })
